language: python
python:
- '3.8'
- '3.10'
- '3.12'
- '3.13'
env:
- DJANGO="Django>=4.2,<4.3"
- DJANGO="Django>=5.0,<5.1"
- DJANGO="Django>=5.1,<5.2"
- DJANGO="Django>=5.2,<5.3"
exclude:
- python: '3.8'
  env: DJANGO="Django>=5.0,<5.1"
- python: '3.8'
  env: DJANGO="Django>=5.1,<5.2"
- python: '3.8'
  env: DJANGO="Django>=5.2,<5.3"
install:
- pip install $DJANGO
- python setup.py sdist
- pip install dist/*.tar.gz
script: script/test
deploy:
  provider: pypi
  user: django-shorturls
  password:
    secure: UXFCQF0oJHLqyd+CH+GB3K46AyPyTvbpm+dUMcdEKNptcT3Px6bff4Xvv5grDZOacPF3rIQupQCZY23/2ZueiJo/XPNzkTphmqI2/dFbg+lWMG1ZCVaWwpox1h7ah1Mgal66eWYiLlZ5Buf7NIRnOQYsffrme3m1xFj0RZbLrM8=
  on:
    tags: true
